# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morp < Formula
  desc "Autonomous development infrastructure generator"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.9.0/morp_1.9.0_darwin_amd64.tar.gz"
      sha256 "1b6b15247a38ade04c0a1725ac10c4c819f2bdead9722579db29b1e906b084db"

      define_method(:install) do
        bin.install "morp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.9.0/morp_1.9.0_darwin_arm64.tar.gz"
      sha256 "09122821990dd45f35d90fd84da1bde51e4b1f641686f209afe12861fc4b6d77"

      define_method(:install) do
        bin.install "morp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.9.0/morp_1.9.0_linux_amd64.tar.gz"
      sha256 "19069ed8f0fef0ef8b9d25e3799f19a00299a36d91ef357bc76520f3f7ef4c9e"
      define_method(:install) do
        bin.install "morp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.9.0/morp_1.9.0_linux_arm64.tar.gz"
      sha256 "b101b39ca8398fca52eb10daf1916b03a10b334f8a7960eef43e1a9dc99b6d59"
      define_method(:install) do
        bin.install "morp"
      end
    end
  end
end
