# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morpheus < Formula
  desc "Autonomous development infrastructure generator"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/morpheus_1.8.1_darwin_amd64.tar.gz"
      sha256 "2ac23ea4ca6ecdd91efd1defd1e1e3eadeb589c63d5603ea8b8249aeb9478429"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/morpheus_1.8.1_darwin_arm64.tar.gz"
      sha256 "dd61e96607000f0b554d1db2081322085636f21270a04158605822f671bc1b00"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/morpheus_1.8.1_linux_amd64.tar.gz"
      sha256 "f72172f359ecfe9b3bd10c36efdfa4b216504d203d164bc79d774a1294cf5f8e"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/morpheus_1.8.1_linux_arm64.tar.gz"
      sha256 "c978e0668c5a927f45529060f2cd75c085ed0851895d6a00fe0092bea0024934"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end
end
