# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morp < Formula
  desc "Autonomous development infrastructure generator"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/morp_1.8.2_darwin_amd64.tar.gz"
      sha256 "439438f39c39658184fec86dc67c596b9b168862da57b926d6cdcfffb03f4376"

      define_method(:install) do
        bin.install "morp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/morp_1.8.2_darwin_arm64.tar.gz"
      sha256 "8bcbc2878bc91f9167e8dcc7d761894706f61b9e036aca0d1a6c4b808fc1e356"

      define_method(:install) do
        bin.install "morp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/morp_1.8.2_linux_amd64.tar.gz"
      sha256 "135fe7b4c53e8501f79e3d5f67bddab3b4f8f8be7f3402494953dca4642730f4"
      define_method(:install) do
        bin.install "morp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/morp_1.8.2_linux_arm64.tar.gz"
      sha256 "c2386a994a93691166a2322b1eac22797205023e0eb88616204d1b96eb70bb15"
      define_method(:install) do
        bin.install "morp"
      end
    end
  end
end
