# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morpheus < Formula
  desc "Autonomous development infrastructure generator"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_darwin_amd64.tar.gz"
      sha256 "7c369c3b05293379ebc28a909546a443bbf8bd6b14948d653ce8c2cc7b19f8dd"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_darwin_arm64.tar.gz"
      sha256 "5cdda6ce40e839cd326f8acfca3498c14162f0c458b917ae05a54a0863c3e181"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_linux_amd64.tar.gz"
      sha256 "7cb015a00f1e6805398361d58ae737b087f4f9569386e9e548a7f999a5bcbc3f"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_linux_arm64.tar.gz"
      sha256 "66112cebc4a03aa60b09cff5f3c7dbfb9c38f32cffd13c85b82012fc7d93a599"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end
end
