# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morpheus < Formula
  desc "Autonomous development infrastructure generator"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_darwin_amd64.tar.gz"
      sha256 "bd038a4d185aa479895be63e62bc7aafed561ddab927126d79e53edd6b21b199"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_darwin_arm64.tar.gz"
      sha256 "da7d83d2323138adb83c45ab0eb6f2f0412374a29b7932d81aa9db63a46c58ed"

      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_linux_amd64.tar.gz"
      sha256 "ff0d98e91a6f7b1a10273ca1ed08cdede37d3db84a1bc0fe17379c6be4276c1a"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/morpheus_1.8.0_linux_arm64.tar.gz"
      sha256 "f387f47ecad78f63d5bac635b32bf2037ed7c257dffd2898df501eda96854642"
      define_method(:install) do
        bin.install "morpheus"
      end
    end
  end
end
