# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neo < Formula
  desc "Meta-CLI orchestrator for the-matrix agent ecosystem"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_darwin_amd64.tar.gz"
      sha256 "8aff3781d18260d45b8a29dd11d8ed069b9dedaee249759cd70e50efa490430c"

      define_method(:install) do
        bin.install "neo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_darwin_arm64.tar.gz"
      sha256 "092e53d7b73be49b0128c4c28c8cb8d0da30b8f89a955e06f7c2f89fbb81c1a5"

      define_method(:install) do
        bin.install "neo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_linux_amd64.tar.gz"
      sha256 "ac93b0c02518796053ff584c2b3fce81727c033d6b997577bfa4d053436a061f"
      define_method(:install) do
        bin.install "neo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_linux_arm64.tar.gz"
      sha256 "a9b923e3d06c216664c82b5b3ef7ba5dd4f00dfad973e9846967f66552f57ba5"
      define_method(:install) do
        bin.install "neo"
      end
    end
  end
end
