# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neo < Formula
  desc "Meta-CLI orchestrator for the-matrix agent ecosystem"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_darwin_amd64.tar.gz"
      sha256 "ab1f7de9a49b566ca19362acefcc8afeaceb772fe427b372b08037c2a32fd64f"

      define_method(:install) do
        bin.install "neo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_darwin_arm64.tar.gz"
      sha256 "c00e561dd7edecb1d8abd05a97af0fbb4d958bf5157900b740a6a008239983be"

      define_method(:install) do
        bin.install "neo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_linux_amd64.tar.gz"
      sha256 "06404c267fc1664f734a920adcff06e8968f1f139a6ba829b79f1fc09a4c8b81"
      define_method(:install) do
        bin.install "neo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/neo_1.8.0_linux_arm64.tar.gz"
      sha256 "eb6582ff1cfbb2dba780f23f21743aeb0b499271a1f9351f7fddb25049fc3ded"
      define_method(:install) do
        bin.install "neo"
      end
    end
  end
end
