# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oracle < Formula
  desc "Knowledge synthesis engine for any tech stack"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/oracle_1.8.0_darwin_amd64.tar.gz"
      sha256 "38e78108f8ea691c832d9b3f7dc5b1c5408573e661127afc6cfcbe54e3d3895c"

      define_method(:install) do
        bin.install "oracle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/oracle_1.8.0_darwin_arm64.tar.gz"
      sha256 "efef435c6a4e17ab052f2787ca6d3ba8e5e63aa3047e3b47423230bbd5e571b5"

      define_method(:install) do
        bin.install "oracle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/oracle_1.8.0_linux_amd64.tar.gz"
      sha256 "b78be4de87fc7794bc33c641131dbfb7d007aae77f2d9660675940ae736ec8ac"
      define_method(:install) do
        bin.install "oracle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/oracle_1.8.0_linux_arm64.tar.gz"
      sha256 "367cdf14548c8ab0067cddef27915d8f6b0dd98873347ca6839c13c55fb4139f"
      define_method(:install) do
        bin.install "oracle"
      end
    end
  end
end
