# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oracle < Formula
  desc "Knowledge synthesis engine for any tech stack"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/oracle_1.8.2_darwin_amd64.tar.gz"
      sha256 "7a2e1f65f7349a41c89394108308cdbbef18884797bb529727444977aa4a2e25"

      define_method(:install) do
        bin.install "oracle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/oracle_1.8.2_darwin_arm64.tar.gz"
      sha256 "da0246e80428323b97f0cbfc749c9ca00529d40c7394c7261db20225179431af"

      define_method(:install) do
        bin.install "oracle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/oracle_1.8.2_linux_amd64.tar.gz"
      sha256 "fb70945f1965c98425bc5bcdf2732b12917dc274b3c73c7e98c3031953db30a1"
      define_method(:install) do
        bin.install "oracle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.2/oracle_1.8.2_linux_arm64.tar.gz"
      sha256 "051c1ace77925faab82ca56e149137b27c3a8a1a8c20e900afc938db2778ec08"
      define_method(:install) do
        bin.install "oracle"
      end
    end
  end
end
