# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trinity < Formula
  desc "Maintenance runtime for Claude Code agent ecosystems"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/trinity_1.8.1_darwin_amd64.tar.gz"
      sha256 "672cc4cb984183e449784aef3213cab90a62392866572d511c8a9f3b2d63ddeb"

      define_method(:install) do
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/trinity_1.8.1_darwin_arm64.tar.gz"
      sha256 "f665e3d6bfce669c2ab3ffe103f2553d46cfb6147bd54b217c718eb0d264a339"

      define_method(:install) do
        bin.install "trinity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/trinity_1.8.1_linux_amd64.tar.gz"
      sha256 "41774b38ea38e370cd95f62afec0c3eb71ad1a1b28d9ddf54f04746cc21d24b4"
      define_method(:install) do
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.1/trinity_1.8.1_linux_arm64.tar.gz"
      sha256 "114ef415902fe8b341876e226e8ba8beb1031aadf5ccf72c0cb1db367e751ceb"
      define_method(:install) do
        bin.install "trinity"
      end
    end
  end
end
