# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trinity < Formula
  desc "Maintenance runtime for Claude Code agent ecosystems"
  homepage "https://github.com/0merUfuk/the-matrix"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/trinity_1.8.0_darwin_amd64.tar.gz"
      sha256 "522f4306d0ecdf0848e247ecc600bc47ac255c03faccfb2c689a7416cca17c54"

      define_method(:install) do
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/trinity_1.8.0_darwin_arm64.tar.gz"
      sha256 "110eae1b16ee5eb8aec56e9f7d6202e503e7d27452234e6506e294bed97bdb3d"

      define_method(:install) do
        bin.install "trinity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/trinity_1.8.0_linux_amd64.tar.gz"
      sha256 "6753c3658c9c8daf910f38b7f71715c11bac32391b8f668616c6eb3745e5c4d1"
      define_method(:install) do
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0merUfuk/the-matrix/releases/download/v1.8.0/trinity_1.8.0_linux_arm64.tar.gz"
      sha256 "dfab4bb84e77bb849e643a4f42882607662f67834519d925fbee79ef1a328aea"
      define_method(:install) do
        bin.install "trinity"
      end
    end
  end
end
